services:
  # MySQL 데이터베이스
  ocean-mysql:
    image: mysql:8.0
    container_name: ocean-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: ocean_db
      MYSQL_USER: ocean_user
      MYSQL_PASSWORD: ocean_pass
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      # 초기화 스크립트
      - ./mysql/init:/docker-entrypoint-initdb.d
      # 커스텀 설정
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      # 데이터 영속성
      - ocean_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ocean-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ocean-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ocean-phpmyadmin
    restart: unless-stopped
    depends_on:
      - ocean-mysql
    environment:
      PMA_HOST: ocean-mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    networks:
      - ocean-network

networks:
  ocean-network:
    driver: bridge

volumes:
  ocean_mysql_data:
    driver: local