name: Deploy Ocean App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          # SSH 키 설정
          echo "$EC2_KEY" | base64 -d > ocean-key.pem
          chmod 600 ocean-key.pem
          
          # EC2에서 배포 스크립트 실행
          ssh -o StrictHostKeyChecking=no -i ocean-key.pem $EC2_USER@$EC2_HOST << 'EOF'
            cd /home/ubuntu/ocean
            git pull origin main
            ./deploy.sh
          EOF